### ISSUE TITLE
Invalid HTML breaking profile page

### ISSUE THREAD

**Issue by 21stcn** [WordPoints/wordpoints#650]
Two issues on line 339 of components/points/admin/includes/functions.php :

`<lable><?php esc_html_e( 'Reason', 'wordpoints' ); ?> <input type="text" name="wordpoints_set_reason" />`

1. 'label' tag mispelled
2.  label tag unclosed

This causes all subsequent profile html (from wordpress core and plugins) to be contained with this label tag

![wordpoints](https://cloud.githubusercontent.com/assets/464034/25326548/faf534ee-28d0-11e7-9f7f-56eebd19872f.png)

**Comment by JDGrimes** [comment]
Thank you for the report @21stcn. That UI will probably be replaced by a different one in the near future, see #579. But if that doesn't happen in the next version of WordPoints, then we'll go ahead and fix this bug in the mean time.
