### ISSUE TITLE
CSS: update .screen-reader-text

### ISSUE THREAD

**Issue by JDGrimes** [WordPoints/wordpoints#743]
[WordPress has updated the rules for this class](https://make.wordpress.org/core/?p=23973), and we should do the same. I think that we only have the rule in the top users CSS.

**Comment by thepriefy** [comment]
Hi,

I've looked through the WordPress docs and some files that contain this CSS class.
- ./src/components/points/assets/css/top-users-rtl.css
- ./src/components/points/assets/css/top-users.css

According to the Wordpress docs, I wanna know how should I edit the CSS value.

For example (from the Wordpress docs),
```
clip: rect(1px, 1px, 1px, 1px);
    -webkit-clip-path: inset(50%);
    clip-path: inset(50%);
```

Thx.

**Comment by JDGrimes** [comment]
@thepriefy Yes. It looks like the `clip` property needs to be updated, and `clip-path` (and `-webkit-clip-path`) added. So removing the current `clip` property and replacing it with the code that you posted would be correct.

Our RTL and minified versions of CSS files are automatically built using Grunt. So you only need to manually edit `top-users.css`, and then run `grunt build` from the command line, and the other files will be updated automatically. (You can set up Grunt by running `npm install` from the command line. If you don't have npm, you can [get it here](https://www.npmjs.com/get-npm).)

**Comment by thepriefy** [comment]
@JDGrimes Thank you for the information about editing and minifying the CSS file. I will do it ASAP. :)

**Comment by thepriefy** [comment]
I got some error while running 'npm install' and 'grunt build'. 
Do you know how to fix this?
@JDGrimes 

![2017-12-06 22_36_12-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/10849586/33669923-51605130-dad6-11e7-8b25-3a0c3a2b970c.jpg)

![2017-12-06 22_36_50-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/10849586/33669934-5539c214-dad6-11e7-8ae9-fc40f668f838.jpg)

**Comment by JDGrimes** [comment]
NPM is notoriously difficult to get working on Windows, unfortunately. I think that npm 5 worked better than the latest version, but I'm not on Windows so I'm not real familiar with it. 

If you'd like, you can just forget about the RTL and minified files, and submit a PR without modifying them; I can then build those files when I merge your PR.

**Comment by thepriefy** [comment]
@JDGrimes I just created a PR for this issue. If there is anything you want me to fix, please tell me. :)

**Comment by JDGrimes** [comment]
Nope, everything is perfect @thepriefy. Thanks so much!
