### ISSUE TITLE
About graph

### ISSUE THREAD

**Issue by m0zart89** [WordPoints/wordpoints#766]
Hello!

I want to draw last points with cumulative effect. What I need to do ? Please give me directions and advices and I will share it ofc

**Comment by JDGrimes** [comment]
Hi @m0zart89,

I think you'll probably want to use the points logs, you can query them with [`WordPoints_Points_Logs_Query`](https://github.com/WordPoints/wordpoints/blob/develop/src/components/points/includes/class-wordpoints-points-logs-query.php).

This issue tracker isn't for support, so I'm going to close this issue.
